import 'dart:convert';
import 'dart:io';

import 'package:chess/chess.dart' as chess;
import 'package:flutter_test/flutter_test.dart';
import 'package:maia_chess/main.dart';

// Expected symbols were generated by the pinned independent TypeScript oracle.
// Real legal positions and sacrifice material come from the Rust corpus; scores
// are synthetic boundary inputs, not claims about how an engine rates a game.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/classification/annotation-boundaries.json')
        .readAsStringSync(),
  ) as Map<String, dynamic>;
  final contexts = (fixture['contexts'] as List).cast<Map<String, dynamic>>();
  final vectors = (fixture['vectors'] as List).cast<List<dynamic>>();
  for (final (contextIndex, context) in contexts.indexed) {
    test('independent EC numeric boundaries: ${context['name']}', () {
      final positions = (context['positions'] as List).cast<String>();
      final moves = (context['moves'] as List).cast<String>();
      final targetPly = moves.length;
      final material = (context['material'] as List).cast<int>();
      final cache = <String, int>{};
      for (var i = 0; i < positions.length; i++) {
        final board = chess.Chess.fromFEN(positions[i]);
        expect(board.game_over, isFalse);
        cache[positions[i]] = MoveClassifier.materialEvaluation(positions[i]);
        expect(cache[positions[i]], material[i], reason: 'Rust material $i');
        if (i < moves.length) {
          expect(
            board.move({
              'from': moves[i].substring(0, 2),
              'to': moves[i].substring(2, 4),
            }),
            isTrue,
            reason: 'legal context move $i',
          );
          // python-chess omits an uncapturable en-passant target; the Dart
          // package retains it. Board, turn, rights and clocks must agree.
          final actualFen = board.fen.split(' ');
          final expectedFen = positions[i + 1].split(' ');
          expect(
            [
              for (final field in [0, 1, 2, 4, 5]) actualFen[field],
            ],
            [
              for (final field in [0, 1, 2, 4, 5]) expectedFen[field],
            ],
          );
          if (expectedFen[3] != '-') expect(actualFen[3], expectedFen[3]);
        }
      }
      final before = chess.Chess.fromFEN(positions[targetPly - 1]);
      expect(
        before.move({
          'from': (context['alternative'] as String).substring(0, 2),
          'to': (context['alternative'] as String).substring(2, 4),
        }),
        isTrue,
      );
      expect(
        material[targetPly - 1] > -material[targetPly] + 100,
        context['sacrifice'],
      );
      final sign = context['color'] == 'white' ? 1 : -1;
      StockfishReview score(
        dynamic packed, {
        List<StockfishLine> lines = const [],
      }) {
        final mate = packed is String
            ? int.parse(packed.substring(1)) * sign
            : null;
        return StockfishReview(
          packed is int ? packed * sign : 0,
          '(none)',
          mate: mate,
          lines: lines,
        );
      }

      StockfishLine line(dynamic packed, String root) {
        final review = score(packed);
        return StockfishLine(
          evaluation: review.evaluation,
          moves: [root],
          mate: review.mate,
        );
      }

      final expected = fixture['expected'][contextIndex] as List;
      final observed = <String>{};
      for (final (index, vector) in vectors.indexed) {
        final playedBest = vector[5] as bool;
        final count = vector[6] as int;
        final roots = playedBest
            ? [moves.last, context['alternative'] as String]
            : [context['alternative'] as String, moves.last];
        final lines = [
          if (count > 0) line(vector[3], roots[0]),
          if (count > 1) line(vector[4], roots[1]),
        ];
        final result = MoveClassifier.classify(
          scores: [
            if (targetPly > 1) score(vector[0]),
            score(vector[1], lines: lines),
            score(vector[2]),
          ],
          positions: positions,
          uciMoves: moves,
          requireReliableComparisons: false,
          materialCache: cache,
        );
        final target = result.where((m) => m.ply == targetPly).toList();
        final actual = target.isEmpty
            ? ''
            : target.single.classification.symbol;
        expect(
          actual,
          expected[index],
          reason: '${context['name']} vector $index ${jsonEncode(vector)}',
        );
        observed.add(actual);
      }
      expect(observed, containsAll(['', '?!', '?', '??']));
      expect(observed, contains(context['sacrifice'] == true ? '!!' : '!'));
      if (context['sacrifice'] == true) expect(observed, contains('!?'));
    });
  }
}
