#!/usr/bin/env python3
"""Regenerate the test-only Maia-3 79M Android inference references."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path


REFERENCE_SOURCE_COMMIT = "1e13597c42d4858b7cfd7cfdae01e297263364b2"
REFERENCE_CHECKPOINT_SHA256 = (
    "3fc6181d5db789b45a15305732148757ae74efa3e0028e81ba335b462dac45c2"
)
MOBILE_MAIA_ONNX_SHA256 = (
    "3454b03ae78baa64a87b345fdb1a457265d912caec531039b074f07eda0d8010"
)
CASES = (
    (
        "initial-1500",
        "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        1500,
        1500,
    ),
    (
        "after-e4-black-1600-vs-2100",
        "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        1600,
        2100,
    ),
    (
        "ruy-lopez-middlegame-1800",
        "r1bq1rk1/1pp1bppp/p1np1n2/4p3/B3P3/2P2N1P/PP1P1PP1/RNBQR1K1 w - - 1 10",
        1800,
        1800,
    ),
    (
        "black-promotion-1200",
        "7k/8/8/8/8/8/1p6/7K b - - 0 1",
        1200,
        1200,
    ),
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def dart_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render(cases: list[dict[str, object]]) -> str:
    lines = [
        "// Generated by tool/generate_maia3_reference.py from the official Maia-3",
        "// PyTorch implementation. This file is test-only and is not packaged in the app.",
        "",
        "class Maia3ReferenceCase {",
        "  const Maia3ReferenceCase({",
        "    required this.name,",
        "    required this.fen,",
        "    required this.selfElo,",
        "    required this.opponentElo,",
        "    required this.topMove,",
        "    required this.legalMoveLogits,",
        "  });",
        "",
        "  final String name;",
        "  final String fen;",
        "  final int selfElo;",
        "  final int opponentElo;",
        "  final String topMove;",
        "  final Map<String, double> legalMoveLogits;",
        "}",
        "",
        "const maia3ReferenceRepository = 'https://github.com/CSSLab/maia3';",
        "const maia3ReferenceSourceCommit =",
        f"    '{REFERENCE_SOURCE_COMMIT}';",
        "const maia3ReferenceModel = 'UofTCSSLab/Maia3-79M/maia3-79m.pt';",
        "const maia3ReferenceCheckpointSha256 =",
        f"    '{REFERENCE_CHECKPOINT_SHA256}';",
        "const mobileMaiaOnnxSha256 =",
        f"    '{MOBILE_MAIA_ONNX_SHA256}';",
        "",
        "const maia3ReferenceCases = <Maia3ReferenceCase>[",
    ]
    for case in cases:
        lines.extend(
            [
                "  Maia3ReferenceCase(",
                f"    name: {dart_string(str(case['name']))},",
                f"    fen: {dart_string(str(case['fen']))},",
                f"    selfElo: {case['selfElo']},",
                f"    opponentElo: {case['opponentElo']},",
                f"    topMove: {dart_string(str(case['topMove']))},",
                "    legalMoveLogits: {",
            ]
        )
        for move, logit in case["legalMoveLogits"].items():
            lines.append(f"      {dart_string(move)}: {logit},")
        lines.extend(["    },", "  ),"])
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--maia3-source", type=Path, required=True)
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument(
        "--onnx",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "assets/models/maia3-79m.onnx",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "integration_test/fixtures/maia3_reference.dart",
    )
    args = parser.parse_args()

    source_commit = subprocess.run(
        ["git", "-C", str(args.maia3_source), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if source_commit != REFERENCE_SOURCE_COMMIT:
        parser.error(
            f"Maia-3 source is {source_commit}; expected {REFERENCE_SOURCE_COMMIT}"
        )
    source_changes = subprocess.run(
        ["git", "-C", str(args.maia3_source), "status", "--porcelain"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    if source_changes:
        parser.error("Maia-3 source checkout must be clean")
    if sha256(args.checkpoint) != REFERENCE_CHECKPOINT_SHA256:
        parser.error("Maia-3 checkpoint SHA-256 does not match the pinned reference")
    if sha256(args.onnx) != MOBILE_MAIA_ONNX_SHA256:
        parser.error("Mobile Maia ONNX SHA-256 does not match the pinned model")

    sys.path.insert(0, str(args.maia3_source))
    import torch
    from torch import nn

    torch.set_num_threads(1)
    torch.set_num_interop_threads(1)

    if not hasattr(nn, "RMSNorm"):
        class RMSNorm(nn.Module):
            """PyTorch 2.2 compatibility matching torch.nn.RMSNorm."""

            def __init__(self, normalized_shape: int, eps: float | None = None) -> None:
                super().__init__()
                self.eps = eps if eps is not None else torch.finfo(torch.float32).eps
                self.weight = nn.Parameter(torch.ones(normalized_shape))

            def forward(self, value: torch.Tensor) -> torch.Tensor:
                scale = value.pow(2).mean(dim=-1, keepdim=True)
                return value * torch.rsqrt(scale + self.eps) * self.weight

        nn.RMSNorm = RMSNorm

    import chess
    from maia3.dataset import tokenize_board
    from maia3.uci import load_model, parse_args
    from maia3.utils import get_all_possible_moves, mirror_move

    config = parse_args(
        [
            "--model",
            "maia3-79m",
            "--checkpoint-path",
            str(args.checkpoint),
            "--device",
            "cpu",
        ]
    )
    model = load_model(config)
    move_indices = {
        move: index for index, move in enumerate(get_all_possible_moves())
    }
    token_batches = []
    for _, fen, _, _ in CASES:
        board = chess.Board(fen)
        if not board.is_valid():
            parser.error(f"Reference case is not a legal chess position: {fen}")
        current = tokenize_board(board)
        token_batches.append(
            torch.cat([current] * 8 + [torch.zeros((64, 1))], dim=1)
        )
    with torch.inference_mode():
        move_logits, _, _ = model(
            torch.stack(token_batches),
            torch.tensor([case[2] for case in CASES], dtype=torch.int64),
            torch.tensor([case[3] for case in CASES], dtype=torch.int64),
        )

    rendered_cases = []
    for index, (name, fen, self_elo, opponent_elo) in enumerate(CASES):
        board = chess.Board(fen)
        expected = {}
        for legal_move in board.legal_moves:
            uci = legal_move.uci()
            normalized = mirror_move(uci) if board.turn == chess.BLACK else uci
            expected[uci] = round(
                float(move_logits[index, move_indices[normalized]].item()), 7
            )
        ordered = sorted(expected, key=lambda move: (-expected[move], move))
        rendered_cases.append(
            {
                "name": name,
                "fen": fen,
                "selfElo": self_elo,
                "opponentElo": opponent_elo,
                "topMove": ordered[0],
                "legalMoveLogits": dict(sorted(expected.items())),
            }
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(rendered_cases))
    print(
        f"Wrote {args.output} from official Maia-3 {REFERENCE_SOURCE_COMMIT}; "
        "run dart format on the generated file"
    )


if __name__ == "__main__":
    main()
