// Generated by tool/generate_maia3_reference.py from the official Maia-3
// PyTorch implementation. This file is test-only and is not packaged in the app.

class Maia3ReferenceCase {
  const Maia3ReferenceCase({
    required this.name,
    required this.fen,
    required this.selfElo,
    required this.opponentElo,
    required this.topMove,
    required this.legalMoveLogits,
  });

  final String name;
  final String fen;
  final int selfElo;
  final int opponentElo;
  final String topMove;
  final Map<String, double> legalMoveLogits;
}

const maia3ReferenceRepository = 'https://github.com/CSSLab/maia3';
const maia3ReferenceSourceCommit = '1e13597c42d4858b7cfd7cfdae01e297263364b2';
const maia3ReferenceModel = 'UofTCSSLab/Maia3-79M/maia3-79m.pt';
const maia3ReferenceCheckpointSha256 =
    '3fc6181d5db789b45a15305732148757ae74efa3e0028e81ba335b462dac45c2';
const mobileMaiaOnnxSha256 =
    '3454b03ae78baa64a87b345fdb1a457265d912caec531039b074f07eda0d8010';

const maia3ReferenceCases = <Maia3ReferenceCase>[
  Maia3ReferenceCase(
    name: 'initial-1500',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    selfElo: 1500,
    opponentElo: 1500,
    topMove: 'e2e4',
    legalMoveLogits: {
      'a2a3': 16.1929379,
      'a2a4': 15.9755545,
      'b1a3': 13.1696739,
      'b1c3': 17.5910606,
      'b2b3': 18.8839588,
      'b2b4': 17.9094181,
      'c2c3': 17.2310295,
      'c2c4': 19.6836052,
      'd2d3': 18.0449448,
      'd2d4': 22.0497437,
      'e2e3': 19.271925,
      'e2e4': 23.0209808,
      'f2f3': 16.0131149,
      'f2f4': 18.3174896,
      'g1f3': 19.5760403,
      'g1h3': 14.0934372,
      'g2g3': 19.0165806,
      'g2g4': 17.6229877,
      'h2h3': 15.8493214,
      'h2h4': 16.1931324,
    },
  ),
  Maia3ReferenceCase(
    name: 'after-e4-black-1600',
    fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',
    selfElo: 1600,
    opponentElo: 1600,
    topMove: 'e7e5',
    legalMoveLogits: {
      'a7a5': 16.1306686,
      'a7a6': 17.0417786,
      'b7b5': 15.3430099,
      'b7b6': 19.2220955,
      'b8a6': 12.2401276,
      'b8c6': 18.8918724,
      'c7c5': 20.9676056,
      'c7c6': 20.2679272,
      'd7d5': 21.2549458,
      'd7d6': 19.5445347,
      'e7e5': 22.3215885,
      'e7e6': 20.571907,
      'f7f5': 17.0881653,
      'f7f6': 15.8552513,
      'g7g5': 16.1034622,
      'g7g6': 19.7168655,
      'g8f6': 19.237154,
      'g8h6': 12.8857813,
      'h7h5': 15.7223768,
      'h7h6': 16.1070213,
    },
  ),
  Maia3ReferenceCase(
    name: 'ruy-lopez-middlegame-1800',
    fen: 'r1bq1rk1/1pp1bppp/p1np1n2/4p3/B3P3/2P2N1P/PP1P1PP1/RNBQR1K1 w - - 1 10',
    selfElo: 1800,
    opponentElo: 1800,
    topMove: 'd2d4',
    legalMoveLogits: {
      'a2a3': 19.2064514,
      'a4b3': 16.5957394,
      'a4b5': 8.9887619,
      'a4c2': 18.7553654,
      'a4c6': 16.2843323,
      'b1a3': 14.4214621,
      'b2b3': 12.1547804,
      'b2b4': 16.1754322,
      'c3c4': 13.9220028,
      'd1b3': 9.8257685,
      'd1c2': 11.3326559,
      'd1e2': 14.4222221,
      'd2d3': 18.4048347,
      'd2d4': 21.420536,
      'e1e2': 10.9246674,
      'e1e3': 10.3337059,
      'e1f1': 10.462925,
      'f3d4': 9.1544228,
      'f3e5': 8.4281483,
      'f3g5': 11.7306089,
      'f3h2': 14.387022,
      'f3h4': 11.5364437,
      'g1f1': 11.1144333,
      'g1h1': 11.6344671,
      'g1h2': 14.3954391,
      'g2g3': 8.2192392,
      'g2g4': 10.8074093,
      'h3h4': 8.4119453,
    },
  ),
  Maia3ReferenceCase(
    name: 'black-promotion-1200',
    fen: '7k/8/8/8/8/8/1p6/7K b - - 0 1',
    selfElo: 1200,
    opponentElo: 1200,
    topMove: 'b2b1q',
    legalMoveLogits: {
      'b2b1b': 15.92274,
      'b2b1n': 15.3519592,
      'b2b1q': 21.5784607,
      'b2b1r': 18.0845547,
      'h8g7': 17.4155045,
      'h8g8': 15.7991962,
      'h8h7': 16.3932381,
    },
  ),
];
