// Generated by tool/generate_maia3_reference.py from the official Maia-3
// PyTorch implementation. This file is test-only and is not packaged in the app.

class Maia3ReferenceCase {
  const Maia3ReferenceCase({
    required this.name,
    required this.fen,
    required this.selfElo,
    required this.opponentElo,
    required this.topMove,
    required this.legalMoveLogits,
  });

  final String name;
  final String fen;
  final int selfElo;
  final int opponentElo;
  final String topMove;
  final Map<String, double> legalMoveLogits;
}

const maia3ReferenceRepository = 'https://github.com/CSSLab/maia3';
const maia3ReferenceSourceCommit = '1e13597c42d4858b7cfd7cfdae01e297263364b2';
const maia3ReferenceModel = 'UofTCSSLab/Maia3-79M/maia3-79m.pt';
const maia3ReferenceCheckpointSha256 =
    '3fc6181d5db789b45a15305732148757ae74efa3e0028e81ba335b462dac45c2';
const mobileMaiaOnnxSha256 =
    '3454b03ae78baa64a87b345fdb1a457265d912caec531039b074f07eda0d8010';

const maia3ReferenceCases = <Maia3ReferenceCase>[
  Maia3ReferenceCase(
    name: 'initial-1500',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    selfElo: 1500,
    opponentElo: 1500,
    topMove: 'e2e4',
    legalMoveLogits: {
      'a2a3': 16.1929302,
      'a2a4': 15.9755774,
      'b1a3': 13.169672,
      'b1c3': 17.591053,
      'b2b3': 18.883955,
      'b2b4': 17.9094105,
      'c2c3': 17.2310181,
      'c2c4': 19.6836128,
      'd2d3': 18.0449352,
      'd2d4': 22.0497398,
      'e2e3': 19.2719383,
      'e2e4': 23.0209846,
      'f2f3': 16.0131035,
      'f2f4': 18.3174915,
      'g1f3': 19.5760517,
      'g1h3': 14.0934439,
      'g2g3': 19.0165768,
      'g2g4': 17.6230049,
      'h2h3': 15.8493242,
      'h2h4': 16.1931267,
    },
  ),
  Maia3ReferenceCase(
    name: 'after-e4-black-1600-vs-2100',
    fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',
    selfElo: 1600,
    opponentElo: 2100,
    topMove: 'e7e5',
    legalMoveLogits: {
      'a7a5': 16.7338924,
      'a7a6': 17.3867512,
      'b7b5': 16.0601654,
      'b7b6': 18.9390621,
      'b8a6': 13.8493729,
      'b8c6': 19.0343666,
      'c7c5': 20.6687584,
      'c7c6': 19.9813995,
      'd7d5': 20.7969379,
      'd7d6': 19.5181007,
      'e7e5': 21.9349346,
      'e7e6': 20.4663277,
      'f7f5': 17.2440987,
      'f7f6': 16.5509796,
      'g7g5': 16.5830803,
      'g7g6': 19.3665924,
      'g8f6': 19.2797985,
      'g8h6': 14.1835709,
      'h7h5': 16.5270729,
      'h7h6': 16.5391541,
    },
  ),
  Maia3ReferenceCase(
    name: 'ruy-lopez-middlegame-1800',
    fen: 'r1bq1rk1/1pp1bppp/p1np1n2/4p3/B3P3/2P2N1P/PP1P1PP1/RNBQR1K1 w - - 1 10',
    selfElo: 1800,
    opponentElo: 1800,
    topMove: 'd2d4',
    legalMoveLogits: {
      'a2a3': 19.2064686,
      'a4b3': 16.5957317,
      'a4b5': 8.9887514,
      'a4c2': 18.7553616,
      'a4c6': 16.2843304,
      'b1a3': 14.421483,
      'b2b3': 12.154788,
      'b2b4': 16.1754456,
      'c3c4': 13.9219856,
      'd1b3': 9.8257809,
      'd1c2': 11.3326712,
      'd1e2': 14.4222145,
      'd2d3': 18.4048386,
      'd2d4': 21.4205494,
      'e1e2': 10.9246664,
      'e1e3': 10.3337097,
      'e1f1': 10.4629259,
      'f3d4': 9.1544342,
      'f3e5': 8.4281445,
      'f3g5': 11.7306175,
      'f3h2': 14.3870268,
      'f3h4': 11.5364447,
      'g1f1': 11.1144304,
      'g1h1': 11.6344738,
      'g1h2': 14.3954382,
      'g2g3': 8.2192411,
      'g2g4': 10.807416,
      'h3h4': 8.4119358,
    },
  ),
  Maia3ReferenceCase(
    name: 'black-promotion-1200',
    fen: '7k/8/8/8/8/8/1p6/7K b - - 0 1',
    selfElo: 1200,
    opponentElo: 1200,
    topMove: 'b2b1q',
    legalMoveLogits: {
      'b2b1b': 15.9227638,
      'b2b1n': 15.3519764,
      'b2b1q': 21.5784836,
      'b2b1r': 18.0845776,
      'h8g7': 17.4154873,
      'h8g8': 15.7991962,
      'h8h7': 16.3932171,
    },
  ),
];
